// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel;

/************************************************************/
/**
 * 
 */
public abstract class Graph {
	
	/**
	 * The different types of graphs which are supported
	 */
	public enum GraphTypes {PETRI, CR};
	
	/**
	 * The type of this graph
	 */
	private GraphTypes graphType;
	/**
	 * 
	 */
	private int ID;
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @param  
	 */
	public void setGraphType(GraphTypes graphType) {
		this.graphType = graphType;
	}
	
	public GraphTypes getGraphType() {
		return this.graphType;
	} 
};
