// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel;

/************************************************************/
/**
 * 
 */
public abstract class Graph {
	
	/**
	 * The different types of graphs which are supported
	 */
	public enum GraphTypes {PETRI, CR};
	
	/**
	 * The type of this graph
	 */
	private GraphTypes graphType;
	
	private static int latestID;	
	/**
	 * 
	 */
	private int ID;
	/**
	 * 
	 */
	private String name;
	
	protected Graph(String name) {
		this.name = name;
		latestID++;
		this.setID(latestID);
	}

	/**
	 * 
	 * @param  
	 */
	public void setGraphType(GraphTypes graphType) {
		this.graphType = graphType;
	}
	
	public GraphTypes getGraphType() {
		return this.graphType;
	}

	public int getID() {
		return ID;
	}

	private void setID(int id) {
		ID = id;
	} 
};
