// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel;

/************************************************************/
/**
 * 
 */
public class Position {
	/**
	 * 
	 */
	protected int xCoord;
	/**
	 * 
	 */
	protected int yCoord;
};
