// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel;

/************************************************************/
/**
 * 
 */
public interface Semantics {

	/**
	 * 
	 */
	public void getPossibleActions();

	/**
	 * 
	 */
	public void executeAction();
};
