// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel;

import java.awt.image.BufferedImage;

/************************************************************/
/**
 * 
 */
public interface Visualization {

	/**
	 * Draws the graph of the class implementing this interface (PetriNet and CrGraph)
	 * 
	 * @return The BufferedImage of the Graph
	 */
	public BufferedImage draw();
};
