// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel;

/************************************************************/
/**
 * 
 */
public interface Visualization {

	/**
	 * 
	 */
	public void draw();
};
