// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.petri;

import RootElement.system.datamodel.Position;

/************************************************************/
/**
 * 
 */
public abstract class PetriObject {
	/**
	 * 
	 */
	protected RootElement.system.datamodel.petri.PetriObject[] incomming;
	/**
	 * 
	 */
	protected RootElement.system.datamodel.petri.PetriObject[] outgoing;
	/**
	 * 
	 */
	protected int id;
	/**
	 * 
	 */
	protected Position pos;
};
