// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.petri;

import java.util.List;

import datamodel.Position;

/************************************************************/
/**
 * 
 */
public abstract class PetriObject {
	/**
	 * 
	 */
	protected List<PetriObject> incomming;
	/**
	 * 
	 */
	protected List<PetriObject> outgoing;
	/**
	 * 
	 */
	protected int id;
	/**
	 * 
	 */
	protected Position pos;
};
