// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.petri;

import java.awt.image.BufferedImage;
import java.util.List;

import datamodel.Graph;
import datamodel.Semantics;
import datamodel.Visualization;
import datamodel.petri.Place;
import datamodel.petri.Transition;

/************************************************************/
/**
 * 
 */
public class Petrinet extends Graph implements Visualization, Semantics {
	/**
	 * 
	 */
	private Place start;
	/**
	 * 
	 */
	private Place end;
	/**
	 * 
	 */
	private List<Transition> transitions;
	/**
	 * 
	 */
	private List<Place> places;

	/**
	 * 
	 */
	public void addArc() {
	}

	@Override
	public void getPossibleActions() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void executeAction() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public BufferedImage draw() {
		// TODO Auto-generated method stub
		return null;
		
	}
};
