// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.petri;

import RootElement.system.datamodel.Graph;
import RootElement.system.datamodel.Semantics;
import RootElement.system.datamodel.Visualization;
import RootElement.system.datamodel.petri.Place;
import RootElement.system.datamodel.petri.Transition;

/************************************************************/
/**
 * 
 */
public class Petrinet extends Graph implements Visualization, Semantics {
	/**
	 * 
	 */
	private Place start;
	/**
	 * 
	 */
	private Place end;
	/**
	 * 
	 */
	private Transition[] transitions;
	/**
	 * 
	 */
	private Place[] places;

	/**
	 * 
	 */
	public void addArc() {
	}
};
