// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.petri;

import datamodel.petri.PetriObject;

/************************************************************/
/**
 * 
 */
public class Place extends PetriObject {
	/**
	 * 
	 */
	private boolean token;
};
