// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.petri;

import RootElement.system.datamodel.petri.PetriObject;

/************************************************************/
/**
 * 
 */
public class Place extends PetriObject {
	/**
	 * 
	 */
	private boolean token;
};
