// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.petri;

import datamodel.Position;
import datamodel.SimulationObject;
import datamodel.petri.PetriObject;

/************************************************************/
/**
 * 
 */
public class Place extends PetriObject implements SimulationObject {
	
	/**
	 * True if this Place holds a token
	 */
	private boolean token;
	
	private boolean latestValue;
	
	public Place(Position pos) {
		super(pos);
		// TODO Auto-generated constructor stub
	}

	public boolean hasToken() {
		return token;
	}

	public void setToken(boolean token) {
		this.token = token;
	}

	@Override
	public void startSimulation() {
		this.latestValue = this.token;		
	}

	@Override
	public void stopSimulation() {
		this.token = this.latestValue;	
	}


};
