// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.petri;

import RootElement.system.datamodel.cr.CrGraph;
import RootElement.system.datamodel.petri.PetriObject;

/************************************************************/
/**
 * 
 */
public class Transition extends PetriObject {
	/**
	 * 
	 */
	private String Name;
	/**
	 * 
	 */
	private CrGraph crgrapgh;
};
