// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.petri;

import datamodel.cr.CrGraph;
import datamodel.petri.PetriObject;

/************************************************************/
/**
 * 
 */
public class Transition extends PetriObject {
	/**
	 * 
	 */
	private String Name;
	/**
	 * 
	 */
	private CrGraph crgrapgh;
};
