// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.DataModel;

/************************************************************/
/**
 * 
 */
public abstract class Graph {
	/**
	 * 
	 */
	private EcorePrimitiveTypes.EEnumerator[] graphType;
	/**
	 * 
	 */
	private int ID;
	/**
	 * 
	 */
	private String name;

	/**
	 * 
	 * @param  
	 */
	public void setGraphType(EcorePrimitiveTypes.EEnumerator null) {
	}
};
