// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.cr;

import RootElement.system.datamodel.cr.Relation;

/************************************************************/
/**
 * 
 */
public class Condition extends Relation {
};
