// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.cr;

import java.util.List;

import datamodel.Graph;
import datamodel.Semantics;
import datamodel.Visualization;
import datamodel.cr.Event;

/************************************************************/
/**
 * 
 */
public class CrGraph extends Graph implements Visualization, Semantics {
	/**
	 * 
	 */
	private List<Event> trace;

	@Override
	public void getPossibleActions() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void executeAction() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void draw() {
		// TODO Auto-generated method stub
		
	}
};
