// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.cr;

import RootElement.system.datamodel.Graph;
import RootElement.system.datamodel.Semantics;
import RootElement.system.datamodel.Visualization;
import RootElement.system.datamodel.cr.Event;

/************************************************************/
/**
 * 
 */
public class CrGraph extends Graph implements Visualization, Semantics {
	/**
	 * 
	 */
	private Event[] trace;
};
