// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.cr;

/************************************************************/
/**
 * 
 */
public abstract class CRObject {
	/**
	 * 
	 */
	protected int ID;
};
