// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.cr;

import datamodel.Position;
import datamodel.cr.CRObject;
import datamodel.petri.Petrinet;

/************************************************************/
/**
 * 
 */
public class Event extends CRObject {
	/**
	 * 
	 */
	private Petrinet petrinet;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private boolean executed;
	/**
	 * 
	 */
	private boolean pending;
	/**
	 * 
	 */
	private Position pos;
};
