// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.cr;

import RootElement.system.datamodel.Position;
import RootElement.system.datamodel.cr.CRObject;
import RootElement.system.datamodel.petri.Petrinet;

/************************************************************/
/**
 * 
 */
public class Event extends CRObject {
	/**
	 * 
	 */
	private Petrinet petrinet;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private boolean executed;
	/**
	 * 
	 */
	private boolean pending;
	/**
	 * 
	 */
	private Position pos;
};
