// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.cr;

import datamodel.cr.CRObject;
import datamodel.cr.Event;

/************************************************************/
/**
 * 
 */
public abstract class Relation extends CRObject {
	/**
	 * 
	 */
	protected Event incomming;
	/**
	 * 
	 */
	protected Event outgoing;
};
