// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.datamodel.cr;

import RootElement.system.datamodel.cr.CRObject;
import RootElement.system.datamodel.cr.Event;

/************************************************************/
/**
 * 
 */
public abstract class Relation extends CRObject {
	/**
	 * 
	 */
	protected Event incomming;
	/**
	 * 
	 */
	protected Event outgoing;
};
