// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datamodel.cr;

import datamodel.cr.Relation;

/************************************************************/
/**
 * 
 */
public class Response extends Relation {
};
