// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package RootElement.system.gui;

import RootElement.system.datamodel.Graph;
import RootElement.system.datamodel.Position;

/************************************************************/
/**
 *
 */
public class GuiController {
	/**
	 * 
	 */
	private Graph[] Graphs;
	/**
	 * 
	 */
	public int activeGraphID;

	/**
	 * 
	 * @param name 
	 * @param graphType 
	 */
	public void CreateGraph(String name, EcorePrimitiveTypes.EEnumerator graphType) {
	}

	/**
	 * 
	 * @param graphID 
	 */
	public void DeleteCrGraph(int graphID) {
	}

	/**
	 * 
	 * @param pos 
	 */
	public void CreatePlace(Position pos) {
	}

	/**
	 * 
	 * @param placeID 
	 */
	public void DeletePlace(int placeID) {
	}

	/**
	 * 
	 * @param pos 
	 * @param name 
	 */
	public void CreateTransition(Position pos, String name) {
	}

	/**
	 * 
	 * @param transitionID 
	 */
	public void DeleteTransition(int transitionID) {
	}

	/**
	 * 
	 * @param incomingID 
	 * @param outgoingID 
	 */
	public void CreateArc(int incomingID, int outgoingID) {
	}

	/**
	 * 
	 * @param incomingID 
	 * @param outgoingID 
	 */
	public void DeleteArc(int incomingID, int outgoingID) {
	}

	/**
	 * 
	 * @param pos 
	 * @param name 
	 */
	public void CreateEvent(Position pos, String name) {
	}

	/**
	 * 
	 * @param eventID 
	 */
	public void DeleteEvent(int eventID) {
	}

	/**
	 * 
	 * @param incomingID 
	 * @param outgoingID 
	 */
	public void CreateResponse(int incomingID, int outgoingID) {
	}

	/**
	 * 
	 * @param crObjID 
	 */
	public void DeleteResponse(int crObjID) {
	}

	/**
	 * 
	 * @param incomingID 
	 * @param outgoingID 
	 */
	public void CreateCondition(int incomingID, undefined outgoingID) {
	}

	/**
	 * 
	 * @param crObjID 
	 */
	public void DeleteCondition(int crObjID) {
	}
};
